import {createRifleView} from './rifle.js';
import {KNIVES,COATINGS,createKnifeView,movementSpread,weaponSound} from './armory.js';
import * as THREE from './three.module.js';
import {ACCURATE_SPEED,accuracyState,newCounterDrill,stepCounterDrill,scoreCounterShot} from './drills.js';
import {GUN,damageBot,newPlayer,stepPlayer,botSlot,jellyStatus} from './gameplay.js';
import {buildBot,buildWarehouse,buildMeatJelly} from './models.js';
import {DEFAULT_CROSSHAIR,parseCode,exportCode,drawCrosshair} from './crosshair.js';
const $=id=>document.getElementById(id), canvas=$('game'),arena=$('arena');
const defaults={sens:.35,dpi:800,duration:60,speed:1,hitbox:'all',color:'#6effd4',sound:true,enemyOutline:'yellow',weaponSkin:'glacial',knife:'karambit',knifeSkin:'nebula',botCount:3,infiniteAmmo:false,bulletTrails:false};
let cfg={...defaults};try{const saved=JSON.parse(localStorage.getItem('blue-root-settings'));if(saved)cfg={...defaults,...saved};}catch{}
function validate(c){if(!Number.isFinite(c.sens)||c.sens<.001||c.sens>10||!Number.isFinite(c.dpi)||c.dpi<50||c.dpi>50000||![30,60,120].includes(c.duration)||![.65,1,1.5].includes(c.speed)||!['all','head'].includes(c.hitbox)||!['#6effd4','#ffffff','#ff526b'].includes(c.color)||typeof c.sound!=='boolean'||![3,5,10].includes(c.botCount)||typeof c.infiniteAmmo!=='boolean'||typeof c.bulletTrails!=='boolean'||!['yellow','red','purple'].includes(c.enemyOutline)||!['glacial','onyx','ember','arc','solar','sakura'].includes(c.weaponSkin)||!KNIVES[c.knife]||!COATINGS[c.knifeSkin])throw new Error('Invalid range settings');return c;}try{validate(cfg)}catch{cfg={...defaults}}
if(!cfg.butterflyRevision){cfg.knife='butterfly';cfg.knifeSkin='gilded';cfg.butterflyRevision=1;}
let mode='flick',running=false,paused=false,finished=false,elapsed=0,hits=0,shots=0,reactSum=0,spawnAt=0,onTarget=0,heldTime=0,holding=false,yaw=0,pitch=0,recoil=0,lastShot=-1,raw=false;
let player=newPlayer(),keys=new Set(),jumpQueued=false,ammo=GUN.magazine,reloadUntil=0,nextShotAt=0,burstShots=0,recoilPitch=0,recoilYaw=0,shotHits=0;
const rifleView=createRifleView();let viewSwayX=0,viewSwayY=0;
let counterDrill=newCounterDrill();let equipped='rifle',inspectStarted=-10,slashStarted=-10,nextSlash=0;const knifeView=createKnifeView();knifeView.build(cfg.knife,cfg.knifeSkin);
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch{ $('overlayTitle').textContent='WebGL is unavailable';$('overlayText').textContent='Enable hardware acceleration or open this range in another desktop browser.';$('start').disabled=true;throw new Error('WebGL unavailable');}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.autoClear=false;
const scene=new THREE.Scene();scene.background=new THREE.Color('#666c67');scene.fog=new THREE.Fog('#72746a',30,80);
const camera=new THREE.PerspectiveCamera(70.5328,16/9,.03,140);camera.position.set(0,1.68,7);camera.rotation.order='YXZ';scene.add(camera);
const hemi=new THREE.HemisphereLight('#dce7e5','#62605a',1.75);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff1d9',1.9);sun.position.set(-13,22,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25,far:65});sun.shadow.bias=-.0007;scene.add(sun);
const mat=(c,extra={})=>new THREE.MeshStandardMaterial({color:c,roughness:.8,...extra});
const concrete=mat('#d1ccbb'),cream=mat('#ece6d3'),dark=mat('#344953'),steel=mat('#6a7b7b'),mint=mat('#69ae9e'),wood=mat('#5c7971'),glass=mat('#62caf3',{metalness:.5,roughness:.18,emissive:'#078ac5',emissiveIntensity:.35}),bark=mat('#dbe7e1',{roughness:.6});
function box(parent,w,h,d,x,y,z,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function cylinder(parent,rt,rb,h,x,y,z,m,n=8){const o=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,n),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
buildWarehouse(scene);
scene.updateMatrixWorld(true);const worldMeshes=[],colliders=[];scene.traverse(o=>{if(o.isMesh){worldMeshes.push(o);const b=new THREE.Box3().setFromObject(o);if(b.max.y>.06&&b.min.y<4)colliders.push(b);}});

const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');const meatJelly=buildMeatJelly(scene);let jellyConsumedAt=null;const interactionRay=new THREE.Raycaster();
function getJellyStatus(){return jellyStatus(jellyConsumedAt,performance.now());}
function canEatJelly(){if(!running||!getJellyStatus().available)return false;const point=meatJelly.position.clone().add(new THREE.Vector3(0,.2,0));if(Math.hypot(player.x-point.x,player.z-point.z)>1.45||Math.abs(player.y-point.y)>.8)return false;scene.updateMatrixWorld(true);const direction=point.clone().sub(camera.position),distance=direction.length();interactionRay.set(camera.position,direction.normalize());interactionRay.far=distance;return interactionRay.intersectObjects(worldMeshes,false).length===0;}
function eatJelly(){if(!canEatJelly())return;jellyConsumedAt=performance.now();meatJelly.visible=false;$('hitmarker').style.opacity='0';tone(320,.2,.035);updateJelly();}
function updateJelly(){const status=getJellyStatus();meatJelly.visible=status.available;$('jellyPrompt').hidden=!canEatJelly();$('dizzyStatus').hidden=!status.dizzy;$('dizzyStatus').textContent='BAD JELLY · AIM DISABLED · '+status.seconds+'s';arena.classList.toggle('dizzy',status.dizzy&&running);if(!running)syncCamera();}

// Arena markings are procedural game textures, not external artwork.
function sign(text,x,y,z,width){const c=document.createElement('canvas');c.width=1024;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle='#354e50';ctx.fillRect(0,0,1024,256);ctx.fillStyle='#c9e1d2';ctx.font='bold 116px Arial';ctx.textAlign='center';ctx.fillText(text,512,170);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const o=new THREE.Mesh(new THREE.PlaneGeometry(width,width/4),new THREE.MeshBasicMaterial({map:t}));o.position.set(x,y,z);scene.add(o);}
sign('STRIKE / 07',0,4.8,-21.60,4.5);
const outlineMaterial=new THREE.MeshBasicMaterial({color:'#ffff00',side:THREE.BackSide});
// Screen-space glow stays equally visible at all target distances.
const maskTarget=new THREE.WebGLRenderTarget(1,1,{depthBuffer:true});
const maskMaterial=new THREE.MeshBasicMaterial({color:0xffffff,toneMapped:false,fog:false});
const maskOccluder=new THREE.MeshBasicMaterial({color:0x000000,toneMapped:false,fog:false});
const glowUniforms={mask:{value:maskTarget.texture},resolution:{value:new THREE.Vector2(1,1)},pixelRatio:{value:1},tint:{value:outlineMaterial.color}};
const glowMaterial=new THREE.ShaderMaterial({transparent:true,depthTest:false,depthWrite:false,toneMapped:false,uniforms:glowUniforms,vertexShader:`varying vec2 uvScreen;void main(){uvScreen=uv;gl_Position=vec4(position.xy,0.,1.);}`,fragmentShader:`uniform sampler2D mask;uniform vec2 resolution;uniform vec3 tint;uniform float pixelRatio;varying vec2 uvScreen;void main(){float center=texture2D(mask,uvScreen).r;float nearRing=0.;float midRing=0.;float farRing=0.;for(int i=0;i<12;i++){float angle=float(i)*6.2831853/12.;vec2 d=vec2(cos(angle),sin(angle))*pixelRatio/resolution;nearRing=max(nearRing,texture2D(mask,uvScreen+d*2.6).r);midRing+=texture2D(mask,uvScreen+d*6.).r/12.;farRing+=texture2D(mask,uvScreen+d*11.).r/12.;}float edge=max(nearRing-center,0.);float halo=(midRing*.85+farRing*.5)*(1.-center);float alpha=clamp(edge*.98+halo,0.,.98);gl_FragColor=vec4(mix(tint,vec3(1.),edge*.22),alpha);}`});
const glowScene=new THREE.Scene(),glowCamera=new THREE.Camera();glowScene.add(new THREE.Mesh(new THREE.PlaneGeometry(2,2),glowMaterial));
function renderOutlineGlow(){const bg=scene.background,clearAlpha=renderer.getClearAlpha(),clearColor=renderer.getClearColor(new THREE.Color());scene.background=null;scene.overrideMaterial=maskMaterial;camera.layers.set(1);renderer.setRenderTarget(maskTarget);renderer.setClearColor(0x000000,0);renderer.clear();camera.layers.set(0);scene.overrideMaterial=maskOccluder;renderer.render(scene,camera);camera.layers.set(1);scene.overrideMaterial=maskMaterial;renderer.render(scene,camera);renderer.setRenderTarget(null);scene.overrideMaterial=null;scene.background=bg;camera.layers.set(0);renderer.setClearColor(clearColor,clearAlpha);renderer.render(glowScene,glowCamera);}
const targets=[],hitMeshes=[];const skins=[['#75c6c6','#e6ede7','#e0b6a2'],['#766da7','#272f45','#ba876d'],['#dcb251','#eee1b3','#a77a60']];
function makeAgent(index){const root=new THREE.Group();root.userData.index=index;scene.add(root);buildBot(root,index);root.traverse(o=>{if(o.isMesh){o.userData.agent=root;o.layers.enable(1);hitMeshes.push(o);}});root.userData.hp=GUN.botHP;root.userData.damageUntil=0;targets.push(root);return root;}
for(let i=0;i<10;i++)makeAgent(i);
function spawn(t){t.userData.hp=GUN.botHP;t.position.set((Math.random()-.5)*12,0,-5-Math.random()*9);t.visible=true;spawnAt=elapsed;}
function arrange(){targets.forEach((t,i)=>{t.userData.hp=GUN.botHP;t.visible=i<cfg.botCount;if(t.visible){const slot=botSlot(i,cfg.botCount);t.position.set(slot.x,0,slot.z);t.userData.baseX=slot.x;t.userData.baseZ=slot.z;}});spawnAt=elapsed;}
arrange();
const FINISHES={solar:{name:'Solar Eclipse',series:'SOLAR COLLECTION',note:'Black titanium. Molten gold core.',accent:'#ffbd57'},sakura:{name:'Sakura Drift',series:'BLOOM COLLECTION',note:'Ivory ceramic. Sculpted pink petals.',accent:'#ff9fcf'},glacial:{name:'Glacial Bloom',series:'CRYSTAL COLLECTION',note:'Arctic alloy. Cyan crystal inlays.',accent:'#6ddcff',body:'#54bbed',trim:'#e4e7d9',type:'root'},onyx:{name:'Sovereign Noir',series:'ROYAL COLLECTION',note:'Obsidian armor. Brushed gold trim.',accent:'#e7bf6a',body:'#202331',trim:'#dcb25f',type:'royal'},ember:{name:'Emberfall',series:'FORGED COLLECTION',note:'Forged gunmetal. Molten amber.',accent:'#ff7648',body:'#332831',trim:'#9e4c35',type:'molten'},arc:{name:'Arc Protocol',series:'ION COLLECTION',note:'Pearl ceramic. Violet energy.',accent:'#bb91ff',body:'#dbdfea',trim:'#72639f',type:'tech'}};
function applySkin(){const f=FINISHES[cfg.weaponSkin];rifleView.build(cfg.weaponSkin);$('equippedName').textContent=f.name+' ◆';$('weaponName').textContent=f.name.toUpperCase();$('weaponFinish').textContent=f.series;document.documentElement.style.setProperty('--skin-accent',f.accent);document.querySelectorAll('[data-skin]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.skin===cfg.weaponSkin));b.querySelector('.equip-label').textContent=b.dataset.skin===cfg.weaponSkin?'EQUIPPED ✓':'EQUIP FINISH ↗';});}
let crosshair={...DEFAULT_CROSSHAIR};try{const stored=localStorage.getItem('blue-root-crosshair');if(stored)crosshair=parseCode(stored).crosshair;}catch{}
function applyCrosshair(){drawCrosshair($('crosshair'),crosshair);$('crosshair').style.position='absolute';}
applySkin();applyCrosshair();
const raycaster=new THREE.Raycaster();let lastSurfaceHit=null;let shotEndpoint=new THREE.Vector3();const bulletTrailMeshes=[];
function currentHit(spread=0){const dizzy=getJellyStatus().dizzy;if(dizzy)spread=Math.max(spread,THREE.MathUtils.degToRad(8));scene.updateMatrixWorld(true);raycaster.setFromCamera(new THREE.Vector2(),camera);if(spread>0){const angle=Math.random()*Math.PI*2,r=Math.sqrt(Math.random())*spread;const offset=new THREE.Vector3(Math.cos(angle)*r,Math.sin(angle)*r,0).applyQuaternion(camera.quaternion);raycaster.ray.direction.add(offset).normalize();}const hit=raycaster.intersectObjects(hitMeshes,false).find(h=>h.object.userData.agent.visible);const wall=raycaster.intersectObjects(worldMeshes,false)[0];const closest=hit&&(!wall||hit.distance<wall.distance)?hit:wall;lastSurfaceHit=closest===wall?wall:null;shotEndpoint=closest?closest.point.clone():raycaster.ray.at(60,new THREE.Vector3());if(dizzy||!hit)return null;if(wall&&wall.distance<hit.distance)return null;if(cfg.hitbox==='head'&&!hit.object.userData.head)return null;return hit;}
const bulletMarks=[];
const impactGeometry=new THREE.CircleGeometry(.025,12),impactMaterial=new THREE.MeshBasicMaterial({color:'#171714',transparent:true,opacity:.9,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2});
function clearBulletMarks(){for(const m of bulletMarks){scene.remove(m.mesh);}bulletMarks.length=0;}
function addBulletMark(){if(!lastSurfaceHit?.face)return;const normal=lastSurfaceHit.face.normal.clone().transformDirection(lastSurfaceHit.object.matrixWorld);if(normal.dot(raycaster.ray.direction)>0)normal.negate();const mark=new THREE.Mesh(impactGeometry,impactMaterial);mark.position.copy(lastSurfaceHit.point).addScaledVector(normal,.004);mark.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal);mark.rotateZ(Math.random()*Math.PI*2);mark.scale.setScalar(.8+Math.random()*.4);scene.add(mark);bulletMarks.push({mesh:mark,born:performance.now()});if(bulletMarks.length>180)scene.remove(bulletMarks.shift().mesh);}
function updateBulletMarks(){const cutoff=performance.now()-30000;while(bulletMarks.length&&bulletMarks[0].born<cutoff)scene.remove(bulletMarks.shift().mesh);}
function updateCounterFeedback(){const el=$('movementFeedback');el.hidden=mode!=='counter'||!running;if(el.hidden)return;const state=accuracyState(player,getJellyStatus().dizzy);el.dataset.state=state.kind;el.querySelector('strong').textContent=counterDrill.armed?state.label:'STRAFE LEFT OR RIGHT';el.querySelector('span').textContent=counterDrill.lastResult;}
function addBulletTrail(){if(!cfg.bulletTrails)return;const start=new THREE.Vector3(.20,-.20,-.55).applyQuaternion(camera.quaternion).add(camera.position);const geometry=new THREE.BufferGeometry().setFromPoints([start,shotEndpoint.clone()]);const material=new THREE.LineBasicMaterial({color:'#ffe9a6',transparent:true,opacity:.95,depthWrite:false,toneMapped:false});const line=new THREE.Line(geometry,material);scene.add(line);bulletTrailMeshes.push({line,age:0});}
function updateBulletTrails(dt){for(let i=bulletTrailMeshes.length-1;i>=0;i--){const trail=bulletTrailMeshes[i];trail.age+=dt;trail.line.material.opacity=.95*(1-trail.age/.16);if(trail.age>=.16||!cfg.bulletTrails){scene.remove(trail.line);trail.line.geometry.dispose();trail.line.material.dispose();bulletTrailMeshes.splice(i,1);}}}
function syncCamera(){const dizzy=getJellyStatus().dizzy&&running&&!reducedMotion.matches,t=performance.now()/1000,wobble=dizzy?Math.sin(t*2.6)*.018:0;camera.position.set(player.x,player.y+player.eye,player.z);camera.rotation.set(Math.max(-1.55,Math.min(1.55,pitch+recoilPitch+wobble)),yaw+recoilYaw+(dizzy?Math.cos(t*2)*.025:0),dizzy?Math.sin(t*1.8)*.026:0);}
function updateAmmo(){if(equipped==='knife'){$('ammoCount').textContent='MELEE';return;}$('ammoCount').textContent=cfg.infiniteAmmo?'∞ / INFINITE':reloadUntil?'RELOADING':ammo+' / '+GUN.magazine;}
function reload(){if(equipped==='knife')return;inspectStarted=-10;if(!running||cfg.infiniteAmmo||reloadUntil||ammo===GUN.magazine)return;reloadUntil=elapsed+GUN.reloadSeconds;burstShots=0;updateAmmo();playWeaponSound('reload');}
let audio;function tone(freq,dur,vol=.03){if(!cfg.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq/3,audio.currentTime+dur);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+dur);}catch{}}
function shoot(){if(equipped==='knife'){slash();return;}if(!running||document.pointerLockElement!==canvas||reloadUntil||elapsed<nextShotAt)return;if(!cfg.infiniteAmmo&&ammo<=0){reload();return;}inspectStarted=-10;if(!cfg.infiniteAmmo)ammo--;shots++;nextShotAt=(elapsed-nextShotAt>=GUN.fireInterval?elapsed:nextShotAt)+GUN.fireInterval;recoil=.028;lastShot=elapsed;const spread=movementSpread(player,burstShots);const hit=currentHit(THREE.MathUtils.degToRad(spread));addBulletTrail();addBulletMark();if(mode==='counter')scoreCounterShot(counterDrill,player,getJellyStatus().dizzy,elapsed);playWeaponSound('shot');if(hit){shotHits++;const t=hit.object.userData.agent,result=damageBot(t.userData.hp,!!hit.object.userData.head);t.userData.hp=result.hp;t.userData.lastDamage=result.damage;t.userData.damageUntil=elapsed+.5;$('hitmarker').style.opacity='1';$('hitmarker').style.color=hit.object.userData.head?'#ffd46b':'#ffffff';tone(hit.object.userData.head?1100:800,.06,.04);if(result.killed){hits++;reactSum+=(elapsed-spawnAt)*1000;spawn(t);}}burstShots++;recoilPitch=Math.min(.105,recoilPitch+THREE.MathUtils.degToRad(burstShots<5?.24:.48));recoilYaw=THREE.MathUtils.degToRad(burstShots<5?0:Math.sin(burstShots*.6)*Math.min(.8,(burstShots-4)*.055));syncCamera();updateAmmo();updateStats();}
function updateStats(){const counter=mode==='counter',tracking=mode==='track';$('score').textContent=counter?counterDrill.clean:tracking?onTarget.toFixed(1):hits;$('accuracy').innerHTML=(counter?(counterDrill.attempts?Math.round(counterDrill.clean/counterDrill.attempts*100):'—'):tracking?(elapsed?Math.round(onTarget/elapsed*100):'—'):(shots?Math.round(shotHits/shots*100):'—'))+'<small>%</small>';$('reaction').innerHTML=(counter?(counterDrill.clean?Math.round(counterDrill.delayTotal/counterDrill.clean):'—'):tracking?heldTime.toFixed(1):(hits?Math.round(reactSum/hits):'—'))+'<small>'+(tracking?'s':'ms')+'</small>';$('time').innerHTML=Math.max(0,Math.ceil(cfg.duration-elapsed))+'<small>s</small>';}
function updateSetup(){outlineMaterial.color.set({yellow:'#ffff00',red:'#ff344b',purple:'#cf63ff'}[cfg.enemyOutline]);$('sensDisplay').textContent=cfg.sens;$('dpiDisplay').textContent=cfg.dpi;$('durationDisplay').textContent=cfg.duration+' s';$('speedDisplay').textContent=cfg.speed===1?'Normal':cfg.speed<1?'Slow':'Fast';$('modeLabel').textContent=({flick:'FLICK SHOTS',track:'TRACKING',counter:'COUNTER-STRAFE'}[mode])+' / '+cfg.duration+' SEC';document.documentElement.style.setProperty('--cross',cfg.color);$('scoreLabel').textContent=mode==='counter'?'CLEAN STOPS':mode==='flick'?'BOTS ELIMINATED':'ON TARGET (S)';$('accuracyLabel').textContent=mode==='counter'?'STOP ACCURACY':mode==='flick'?'ACCURACY':'TIME ON TARGET';$('reactionLabel').textContent=mode==='counter'?'STOP → SHOT':mode==='flick'?'AVG. ELIMINATION':'TRIGGER HELD';$('coach').textContent=mode==='counter'?'Strafe with A or D, stop, then fire one shot. Tap the opposite key to brake faster. Move again for your next rep.':mode==='flick'?'Hold fire to spray. Pull down to control recoil; stop or crouch for tighter shots.':'Hold fire and track the target. Move with WASD; reload with R.';updateStats();}
function reset(){equipped='rifle';inspectStarted=-10;slashStarted=-10;nextSlash=0;refreshEquipped();clearBulletMarks();counterDrill=newCounterDrill();jellyConsumedAt=null;meatJelly.visible=true;arena.classList.remove('dizzy');$('jellyPrompt').hidden=true;$('dizzyStatus').hidden=true;player=newPlayer();keys.clear();jumpQueued=false;ammo=GUN.magazine;reloadUntil=0;nextShotAt=0;burstShots=0;recoilPitch=0;recoilYaw=0;shotHits=0;syncCamera();updateAmmo();$('overlayEyebrow').textContent='MAKE EVERY SHOT COUNT';elapsed=0;hits=0;shots=0;reactSum=0;onTarget=0;heldTime=0;holding=false;spawnAt=0;finished=false;paused=false;yaw=0;pitch=0;camera.rotation.set(0,0,0);arrange();updateStats();}
function showOverlay(title,text,button){$('overlay').hidden=false;$('overlayTitle').textContent=title;$('overlayText').textContent=text;$('start').innerHTML=button+' <span>↗</span>';}
async function lock(){if(!canvas.requestPointerLock){showOverlay('Desktop mouse needed','This browser does not support mouse capture. Try desktop Chrome or Edge.','Try again');return;}try{await canvas.requestPointerLock({unadjustedMovement:true});raw=true;}catch{try{await canvas.requestPointerLock();raw=false;}catch{showOverlay('Mouse capture blocked','Click again to capture your mouse, or open the range in a full browser tab.','Try again');}}$('inputState').textContent=raw?'RAW MOUSE INPUT':'STANDARD MOUSE INPUT';}
$('start').onclick=()=>{if(!paused)reset();lock();};
document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement===canvas){running=true;paused=false;$('overlay').hidden=true;}else if(running){running=false;holding=false;keys.clear();jumpQueued=false;if(!finished){paused=true;showOverlay('Take a breath.','Your session is paused. Jump back in whenever you’re ready.','Resume session');}}});
document.addEventListener('pointerlockerror',()=>{if(document.pointerLockElement!==canvas&&!running)$('startHint').textContent='Mouse capture was denied. Click again, or use a full desktop browser tab.';});
document.addEventListener('mousemove',e=>{if(!running||document.pointerLockElement!==canvas)return;viewSwayX=Math.max(-.025,Math.min(.025,viewSwayX-e.movementX*.0003));viewSwayY=Math.max(-.018,Math.min(.018,viewSwayY+e.movementY*.0003));const scale=cfg.sens*.07*Math.PI/180;yaw-=e.movementX*scale;pitch=Math.max(-Math.PI/2+.01,Math.min(Math.PI/2-.01,pitch-e.movementY*scale));syncCamera();});
document.addEventListener('mousedown',e=>{if(e.button!==0||!running)return;holding=true;shoot();});document.addEventListener('mouseup',e=>{if(e.button===0)holding=false;});window.addEventListener('blur',()=>{holding=false;keys.clear();jumpQueued=false;if(running)document.exitPointerLock();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){holding=false;document.exitPointerLock();}});
document.addEventListener('keydown',e=>{if(!running||document.pointerLockElement!==canvas)return;if(['KeyW','KeyA','KeyS','KeyD','Space','ControlLeft','ControlRight','KeyR','KeyT','KeyE','KeyC','KeyF','Digit1','Digit3'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Digit1'&&!e.repeat)equip('rifle');if(e.code==='Digit3'&&!e.repeat)equip('knife');if(e.code==='KeyF'&&!e.repeat)inspectWeapon();if(e.code==='Space'&&!e.repeat)jumpQueued=true;if(e.code==='KeyR'&&!e.repeat)reload();if(e.code==='KeyE'&&!e.repeat)eatJelly();if(e.code==='KeyC'&&!e.repeat)clearBulletMarks();if(e.code==='KeyT'&&!e.repeat){reset();running=true;}});
document.addEventListener('keyup',e=>{keys.delete(e.code);if(running&&['Space','ControlLeft','ControlRight'].includes(e.code))e.preventDefault();});
function setMode(m){if(!['flick','track','counter'].includes(m))throw new Error('Unknown mode');mode=m;running=false;reset();document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));showOverlay(mode==='counter'?'Move. Stop. Shoot.':mode==='flick'?'Your next level starts here.':'Stay with the motion.',mode==='counter'?'Strafe left or right, wait for READY, then shoot. Every fresh strafe starts a new rep.':mode==='flick'?`${cfg.duration} seconds. Agent targets. Just you and your aim.`:'Hold left click and keep your crosshair on the moving agent.','Enter the range');updateSetup();}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
const form=$('settingsForm');function openSettings(){if(running)document.exitPointerLock();for(const [k,v]of Object.entries(cfg)){if(!form.elements[k])continue;if(form.elements[k].type==='checkbox')form.elements[k].checked=v;else form.elements[k].value=v;}updateCm();$('settings').showModal();}
function updateCm(){const s=Number(form.elements.sens.value),d=Number(form.elements.dpi.value);$('cm360').textContent=s>0&&d>0?(360/(s*.07*d)*2.54).toFixed(2)+' cm / 360°':'Enter sensitivity and DPI';}
$('settingsButton').onclick=openSettings;$('tuneButton').onclick=openSettings;$('closeSettings').onclick=()=>$('settings').close();form.oninput=updateCm;
form.onsubmit=e=>{e.preventDefault();const f=new FormData(form);cfg=validate({...cfg,sens:+f.get('sens'),dpi:+f.get('dpi'),duration:+f.get('duration'),speed:+f.get('speed'),hitbox:f.get('hitbox'),enemyOutline:f.get('enemyOutline'),sound:f.has('sound'),botCount:+f.get('botCount'),infiniteAmmo:f.has('infiniteAmmo'),bulletTrails:f.has('bulletTrails')});try{localStorage.setItem('blue-root-settings',JSON.stringify(cfg));}catch{}$('settings').close();setMode(mode);};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await arena.requestFullscreen();}catch{$('arenaHint').textContent='FULLSCREEN UNAVAILABLE IN THIS BROWSER';}};
function resize(){const w=arena.clientWidth,h=arena.clientHeight;renderer.setSize(w,h,false);const pr=renderer.getPixelRatio();maskTarget.setSize(Math.round(w*pr),Math.round(h*pr));glowUniforms.resolution.value.set(Math.round(w*pr),Math.round(h*pr));glowUniforms.pixelRatio.value=pr;camera.aspect=w/h;camera.fov=THREE.MathUtils.radToDeg(2*Math.atan(Math.tan(THREE.MathUtils.degToRad(103/2))/camera.aspect));camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(arena);resize();updateSetup();
const botLabels=targets.map(()=>{const el=document.createElement('div');el.className='bot-health';arena.append(el);return el;});
function updateBotLabels(){targets.forEach((t,i)=>{const el=botLabels[i],p=t.position.clone().add(new THREE.Vector3(0,2.02,0)).project(camera);const visible=t.visible&&p.z>-1&&p.z<1&&Math.abs(p.x)<1&&Math.abs(p.y)<1;el.hidden=!visible;if(!visible)return;el.style.left=(p.x*.5+.5)*100+'%';el.style.top=(-p.y*.5+.5)*100+'%';el.innerHTML='<span>'+t.userData.hp+' / 150</span><i><b style="width:'+(t.userData.hp/150*100)+'%"></b></i>'+(t.userData.damageUntil>elapsed?'<strong>−'+t.userData.lastDamage+'</strong>':'');});}
updateAmmo();
let prev=performance.now(),uiAccum=0;
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-prev)/1000,.05);prev=now;if(running){elapsed+=dt;stepPlayer(player,keys,yaw,dt,colliders,jumpQueued);jumpQueued=false;if(mode==='counter')stepCounterDrill(counterDrill,player,keys.has('KeyA')||keys.has('KeyD'),dt,elapsed);if(!holding||reloadUntil){const recovery=Math.exp(-dt*9);recoilPitch*=recovery;recoilYaw*=recovery;if(elapsed-lastShot>.25)burstShots=0;}syncCamera();if(reloadUntil&&elapsed>=reloadUntil){reloadUntil=0;ammo=GUN.magazine;updateAmmo();}if(holding)shoot();if(mode==='track'){targets.forEach((t,index)=>{if(!t.visible)return;const phase=index*.9;t.position.x=t.userData.baseX+Math.sin(elapsed*cfg.speed*1.15+phase)*1.1;t.position.z=t.userData.baseZ+Math.sin(elapsed*cfg.speed*.6+phase)*.7;t.userData.legs.forEach((l,i)=>l.rotation.x=Math.sin(elapsed*cfg.speed*10+i*Math.PI)*.15);});if(holding&&equipped==='rifle'){heldTime+=dt;if(currentHit()){onTarget+=dt;$('hitmarker').style.opacity='.6';}else $('hitmarker').style.opacity='0';}}if(elapsed>=cfg.duration){elapsed=cfg.duration;finished=true;running=false;holding=false;paused=false;document.exitPointerLock();showOverlay('Rep complete.',mode==='counter'?`${counterDrill.clean} clean stops / ${counterDrill.attempts} attempts · ${counterDrill.clean?Math.round(counterDrill.delayTotal/counterDrill.clean):0} ms from stop to shot.`:mode==='flick'?`${hits} eliminations · ${shots?Math.round(shotHits/shots*100):0}% accuracy · ${hits?Math.round(reactSum/hits):0} ms average. Try another clean rep.`:`${Math.round(onTarget/cfg.duration*100)}% time on target · ${onTarget.toFixed(1)} seconds connected. Keep it smooth.`,'Run it again');$('overlayEyebrow').textContent='SESSION COMPLETE';updateStats();}uiAccum+=dt;if(uiAccum>.1){updateStats();uiAccum=0;}}
updateJelly();updateCounterFeedback();updateBulletMarks();updateBulletTrails(dt);recoil*=Math.exp(-dt*22);if(elapsed-lastShot>.09)$('hitmarker').style.opacity='0';renderer.clear();renderer.render(scene,camera);renderOutlineGlow();updateBotLabels();updateViewmodel(now);}
requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_training_state',description:'Read the current aim trainer settings and session results.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode,settings:{...cfg},running,paused,elapsed,hits,shots,onTargetSeconds:onTarget,player:{...player},ammo,reloading:!!reloadUntil,jelly:getJellyStatus(),counterDrill:{...counterDrill},bulletMarks:bulletMarks.length})})).catch(()=>{});}catch{}}
function playWeaponSound(kind){if(!cfg.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();weaponSound(audio,kind,equipped==='knife'?cfg.knifeSkin:cfg.weaponSkin);}catch{}}
function refreshEquipped(){const knife=equipped==='knife';$('weaponSlot').textContent=knife?'03 / MELEE':'01 / PRIMARY';$('weaponName').textContent=knife?KNIVES[cfg.knife].toUpperCase():FINISHES[cfg.weaponSkin].name.toUpperCase();$('weaponFinish').textContent=knife?COATINGS[cfg.knifeSkin].name+' COLLECTION':FINISHES[cfg.weaponSkin].series;updateAmmo();}
function equip(slot){equipped=slot;holding=false;inspectStarted=-10;reloadUntil=0;burstShots=0;recoilPitch=0;recoilYaw=0;refreshEquipped();playWeaponSound('equip');}
function inspectWeapon(){if(reloadUntil)return;holding=false;inspectStarted=elapsed;playWeaponSound('inspect');}
function slash(){if(!running||document.pointerLockElement!==canvas||elapsed<nextSlash)return;inspectStarted=-10;slashStarted=elapsed;nextSlash=elapsed+.55;playWeaponSound('slash');const hit=currentHit();if(!hit||hit.distance>2.1)return;const bot=hit.object.userData.agent;bot.userData.hp=Math.max(0,bot.userData.hp-75);bot.userData.lastDamage=75;bot.userData.damageUntil=elapsed+.5;$('hitmarker').style.opacity='1';lastShot=elapsed;if(bot.userData.hp===0)spawn(bot);}
function updateViewmodel(now){const duration=equipped==='knife'&&cfg.knife==='butterfly'?3.4:2.4;const age=elapsed-inspectStarted,t=age>=0&&age<duration?age/duration:0;const swing=elapsed-slashStarted,attack=swing>=0&&swing<.4?swing/.4:0;viewSwayX*=.88;viewSwayY*=.88;if(equipped==='knife'){knifeView.render(renderer,camera.aspect,1,now,t,attack,reducedMotion.matches);}else{rifleView.render(renderer,camera.aspect,now,{inspect:t,kick:recoil,reload:reloadUntil?1-Math.max(0,reloadUntil-elapsed)/GUN.reloadSeconds:0,speed:running?player.speed:0,swayX:viewSwayX,swayY:viewSwayY,reduced:reducedMotion.matches});}const spread=movementSpread(player,burstShots);$('spreadRing').hidden=equipped==='knife'||!running;$('spreadRing').style.width=$('spreadRing').style.height=(12+spread*12)+'px';$('spreadRing').style.opacity=spread>.2?'.65':'0';}
function persistSetup(){try{localStorage.setItem('blue-root-settings',JSON.stringify(cfg));}catch{}}
for(const [key,f]of Object.entries(FINISHES)){const b=document.createElement('button');b.dataset.skin=key;b.className='skin-card';b.style.setProperty('--finish',f.accent);b.setAttribute('aria-pressed',String(cfg.weaponSkin===key));b.innerHTML=`<div class="skin-art"><img data-preview="${key}" alt="${f.name} 3D rifle"><span>◆ ${f.series}</span></div><div class="skin-copy"><h3>${f.name}</h3><p>${f.note}</p><span class="equip-label">${cfg.weaponSkin===key?'EQUIPPED ✓':'EQUIP FINISH ↗'}</span></div>`;b.onclick=()=>{cfg.weaponSkin=key;applySkin();equip('rifle');persistSetup();};$('skinGrid').append(b);}
$('collectionButton').onclick=()=>{if(running)document.exitPointerLock();$('collection').showModal();};$('closeCollection').onclick=()=>$('collection').close();
let draft={...crosshair};const controls=[['length','Inner length',0,20,1],['thickness','Inner thickness',0,10,1],['gap','Inner gap',0,20,1],['opacity','Inner opacity',0,1,.1],['outerLength','Outer length',0,20,1],['outerThickness','Outer thickness',0,10,1],['outerGap','Outer gap',0,40,1],['outerOpacity','Outer opacity',0,1,.1],['dotSize','Dot size',1,6,1],['dotOpacity','Dot opacity',0,1,.1],['outlineWidth','Outline width',1,6,1],['outlineOpacity','Outline opacity',0,1,.1]];
for(const [key,label,min,max,step]of controls){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.type='number';input.id='ch_'+key;input.min=min;input.max=max;input.step=step;input.oninput=()=>{if(input.value!==''&&input.checkValidity()){draft[key]=Number(input.value);drawCrosshair($('crosshairPreview'),draft);}};l.append(input);$('crosshairControls').append(l);}
function refreshDraft(){for(const [k]of controls)$('ch_'+k).value=draft[k];$('chColor').value=draft.color;for(const [id,key]of [['chOutline','outline'],['chDot','dot'],['chInner','inner'],['chOuter','outer']])$(id).checked=draft[key];drawCrosshair($('crosshairPreview'),draft);}
$('crosshairButton').onclick=()=>{draft={...crosshair};refreshDraft();$('crosshairDialog').showModal();};$('closeCrosshair').onclick=()=>$('crosshairDialog').close();$('chColor').oninput=e=>{draft.color=e.target.value;drawCrosshair($('crosshairPreview'),draft);};for(const [id,key]of [['chOutline','outline'],['chDot','dot'],['chInner','inner'],['chOuter','outer']])$(id).onchange=e=>{draft[key]=e.target.checked;drawCrosshair($('crosshairPreview'),draft);};
$('importCode').onclick=()=>{try{const imported=parseCode($('crosshairCode').value);draft=imported.crosshair;refreshDraft();$('codeStatus').textContent=imported.warnings.length?'Imported with limitations: '+imported.warnings.join(' '):'Primary crosshair imported. Preview it, then choose Equip crosshair.';}catch(e){$('codeStatus').textContent=e.message;}};
$('exportCode').onclick=async()=>{const code=exportCode(draft);$('crosshairCode').value=code;try{await navigator.clipboard.writeText(code);$('codeStatus').textContent='Copied. In Valorant: Settings → Crosshair → Import Profile Code. Exchange has not been client-tested.';}catch{$('crosshairCode').focus();$('crosshairCode').select();$('codeStatus').textContent='Select and copy the code above. Clipboard access is unavailable.';}};
$('saveCrosshair').onclick=()=>{for(const [key]of controls){if(!$('ch_'+key).reportValidity())return;}crosshair={...draft};applyCrosshair();try{localStorage.setItem('blue-root-crosshair',exportCode(crosshair));}catch{}$('crosshairDialog').close();};

for(const [id,name] of Object.entries(KNIVES))$('knifeType').add(new Option(name,id));for(const [id,c] of Object.entries(COATINGS))$('knifeSkin').add(new Option(c.name,id));$('knifeType').value=cfg.knife;$('knifeSkin').value=cfg.knifeSkin;$('equipKnife').onclick=()=>{cfg.knife=$('knifeType').value;cfg.knifeSkin=$('knifeSkin').value;knifeView.build(cfg.knife,cfg.knifeSkin);equip('knife');persistSetup();$('knifeEquipped').textContent=COATINGS[cfg.knifeSkin].name+' '+KNIVES[cfg.knife]+' equipped';};

// Collection previews come from the same 3D geometry used during play.
try{const previewRenderer=new THREE.WebGLRenderer({alpha:true,antialias:true});previewRenderer.setSize(480,320);previewRenderer.setClearColor(0x142430,1);const previewView=createRifleView();for(const key of Object.keys(FINISHES)){previewView.build(key);document.querySelector('[data-preview="'+key+'"]').src=previewView.thumbnail(previewRenderer);}previewRenderer.dispose();}catch{document.querySelectorAll('[data-preview]').forEach(el=>el.hidden=true);}
