export const GUN={magazine:25,fireInterval:1/9.75,reloadSeconds:2.5,bodyDamage:40,headDamage:160,botHP:150};
export function damageBot(hp,head){const damage=head?GUN.headDamage:GUN.bodyDamage;return {damage,hp:Math.max(0,hp-damage),killed:hp<=damage};}
export function newPlayer(){return {x:0,y:0,z:7,vx:0,vz:0,vy:0,grounded:true,crouched:false,eye:1.68,speed:0};}
const radius=.27;
function overlaps(p,b,height){return p.x+radius>b.min.x&&p.x-radius<b.max.x&&p.z+radius>b.min.z&&p.z-radius<b.max.z&&p.y+height>b.min.y+.002&&p.y<b.max.y-.002;}
export function stepPlayer(p,keys,yaw,dt,colliders,jump=false){const wantCrouch=keys.has('ControlLeft')||keys.has('ControlRight');p.crouched=wantCrouch||(p.crouched&&colliders.some(b=>overlaps(p,b,1.8)));const height=p.crouched?1.05:1.8;let right=Number(keys.has('KeyD'))-Number(keys.has('KeyA')),forward=Number(keys.has('KeyW'))-Number(keys.has('KeyS'));const len=Math.hypot(right,forward);if(len){right/=len;forward/=len;}const speed=p.crouched?2.25:5.4,desiredX=(right*Math.cos(yaw)-forward*Math.sin(yaw))*speed,desiredZ=(-right*Math.sin(yaw)-forward*Math.cos(yaw))*speed;const changeX=desiredX-p.vx,changeZ=desiredZ-p.vz,change=Math.hypot(changeX,changeZ);const reversing=len>0&&(desiredX*p.vx+desiredZ*p.vz)<0,acceleration=p.grounded?(len?(reversing?70:45):32):(len?8:1);const fraction=change?Math.min(1,acceleration*dt/change):0;p.vx+=changeX*fraction;p.vz+=changeZ*fraction;const dx=p.vx*dt,dz=p.vz*dt;const steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.08));const startX=p.x,startZ=p.z;for(let i=0;i<steps;i++){const oldX=p.x;p.x=Math.max(-14.3,Math.min(14.3,p.x+dx/steps));if(colliders.some(b=>overlaps(p,b,height))){p.x=oldX;p.vx=0;}const oldZ=p.z;p.z=Math.max(-21.2,Math.min(12.4,p.z+dz/steps));if(colliders.some(b=>overlaps(p,b,height))){p.z=oldZ;p.vz=0;}}p.speed=Math.hypot(p.x-startX,p.z-startZ)/Math.max(dt,.0001);if(jump&&p.grounded){p.vy=7.2;p.grounded=false;}const oldY=p.y;p.vy-=20*dt;let nextY=p.y+p.vy*dt;p.grounded=false;for(const b of colliders){if(p.x+radius<=b.min.x||p.x-radius>=b.max.x||p.z+radius<=b.min.z||p.z-radius>=b.max.z)continue;if(p.vy<=0&&oldY>=b.max.y-.003&&nextY<=b.max.y){nextY=b.max.y;p.vy=0;p.grounded=true;}else if(p.vy>0&&oldY+height<=b.min.y+.003&&nextY+height>=b.min.y){nextY=b.min.y-height;p.vy=0;}}if(nextY<=0){nextY=0;p.vy=0;p.grounded=true;}p.y=nextY;p.eye+=( (p.crouched?.96:1.68)-p.eye)*(1-Math.exp(-18*dt));return p;}
export function botSlot(index,count){if(![3,5,10].includes(count)||!Number.isInteger(index)||index<0||index>=count)throw new Error('Invalid bot slot');const columns=Math.min(count,5);return {x:((index%columns)-(columns-1)/2)*3,z:-8-Math.floor(index/columns)*5};}
export const JELLY_DURATION_MS=15000;
export function jellyStatus(consumedAt,now){const remainingMs=consumedAt===null?0:Math.max(0,consumedAt+JELLY_DURATION_MS-now);return {dizzy:remainingMs>0,available:remainingMs===0,seconds:Math.ceil(remainingMs/1000)};}
